name: Publish Docs
on:
  push:
    branches:
      - docs
  pull_request:
    branches:
      - docs

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Install DocFX
        run: dotnet tool restore

      - name: Build DocFX
        run: dotnet docfx docs/docfx.json

      - name: Deploy Live
        if: github.ref == 'refs/heads/docs'
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site/
          publish_branch: docs-live
